CREATE TABLE CLIENT(
    ID SERIAL,
    NAME VARCHAR(50),
    LASTNAME VARCHAR(50),
    BIRTHDAY DATE,
    PHONE VARCHAR(20),
    EMAIL VARCHAR(50),
    ADDRESS VARCHAR(100),
    CONSTRAINT CLIENT_PK PRIMARY KEY (ID)
);

CREATE TABLE BALANCE(
    ID SERIAL,
    CREATEDDATE TIMESTAMP,
    ACCOUNT VARCHAR(20),
    BALANCE DECIMAL(8,2),
    CLIENT_ID SERIAL NOT NULL,
    CONSTRAINT BALANCE_PK PRIMARY KEY (ID),
    CONSTRAINT CLIENT_FK FOREIGN KEY (CLIENT_ID)
    REFERENCES CLIENT(ID),
    CONSTRAINT CLIENT_ACCOUNT_UK UNIQUE (ACCOUNT,CLIENT_ID)
);

CREATE TABLE BALANCE_TRANSACTIONS(
    ID SERIAL,
    CREATEDDATE TIMESTAMP,
    CLIENT SERIAL NOT NULL,
    ACCOUNT VARCHAR(20),
    AMOUNT DECIMAL(10,2),
    BALANCE_ID SERIAL NOT NULL,
    CONSTRAINT BALANCE_TRANSACTIONS_PK PRIMARY KEY (ID),
    CONSTRAINT BALANCE_TRANSACTIONS_CLIENT_FK FOREIGN KEY (CLIENT)
    REFERENCES CLIENT(ID),
    CONSTRAINT BALANCE_TRANSACTIONS_BALANCE_FK FOREIGN KEY (BALANCE_ID)
    REFERENCES BALANCE(ID)
);



INSERT INTO CLIENT(ID,NAME,LASTNAME,BIRTHDAY,PHONE,EMAIL,ADDRESS) VALUES(1,'ROBERTO','RAMIREZ','1994/12/31','77885566','robert@gmail.com','san salvador');
INSERT INTO CLIENT(ID,NAME,LASTNAME,BIRTHDAY,PHONE,EMAIL,ADDRESS) VALUES(2,'CARLOS','RUIZ','1984/12/31','77885599','carlos@gmail.com','san salvador');
INSERT INTO CLIENT(ID,NAME,LASTNAME,BIRTHDAY,PHONE,EMAIL,ADDRESS) VALUES(3,'IVAN','DUQUE','1974/12/31','77885533','ivan@gmail.com','san salvador');
INSERT INTO CLIENT(ID,NAME,LASTNAME,BIRTHDAY,PHONE,EMAIL,ADDRESS) VALUES(4,'HELGA','SALAZAR','2004/12/31','77885511','helga@gmail.com','san salvador');
INSERT INTO CLIENT(ID,NAME,LASTNAME,BIRTHDAY,PHONE,EMAIL,ADDRESS) VALUES(5,'DANIEL','RAMIREZ','1999/12/31','77885544','daniel@gmail.com','san salvador');

